# Complete reaction information from Rxn_RBC.txt
REACTION_INFO_COMPLETE = {
    # Glycolysis
    'VHK': {'name': 'Hexokinase', 'reaction': 'GLC + ATP → G6P + ADP', 'substrates': ['GLC', 'ATP'], 'products': ['G6P', 'ADP']},
    'VPGI': {'name': 'Phosphoglucose Isomerase', 'reaction': 'G6P ⇌ F6P', 'substrates': ['G6P'], 'products': ['F6P']},
    'VPFK': {'name': 'Phosphofructokinase', 'reaction': 'F6P + ATP → F16BP + ADP', 'substrates': ['F6P', 'ATP'], 'products': ['F16BP', 'ADP']},
    'VFDPA': {'name': 'Aldolase', 'reaction': 'F16BP ⇌ DHCP + GA3P', 'substrates': ['F16BP'], 'products': ['DHCP', 'GA3P']},
    'VTPI': {'name': 'Triose Phosphate Isomerase', 'reaction': 'DHCP ⇌ GA3P', 'substrates': ['DHCP'], 'products': ['GA3P']},
    'VGAPDH': {'name': 'Glyceraldehyde-3-P Dehydrogenase', 'reaction': 'GA3P + NAD ⇌ B13PG + NADH', 'substrates': ['GA3P', 'NAD'], 'products': ['B13PG', 'NADH']},
    'VPGK': {'name': 'Phosphoglycerate Kinase', 'reaction': 'B13PG + ADP ⇌ P3G + ATP', 'substrates': ['B13PG', 'ADP'], 'products': ['P3G', 'ATP']},
    'VPGM': {'name': 'Phosphoglycerate Mutase', 'reaction': 'P3G ⇌ P2G', 'substrates': ['P3G'], 'products': ['P2G']},
    'VENOPGM': {'name': 'Enolase', 'reaction': 'P2G ⇌ PEP', 'substrates': ['P2G'], 'products': ['PEP']},
    'VPK': {'name': 'Pyruvate Kinase', 'reaction': 'PEP + ADP → PYR + ATP', 'substrates': ['PEP', 'ADP'], 'products': ['PYR', 'ATP']},
    'VLDH': {'name': 'Lactate Dehydrogenase', 'reaction': 'PYR + NADH ⇌ LAC + NAD', 'substrates': ['PYR', 'NADH'], 'products': ['LAC', 'NAD']},
    
    # Pentose Phosphate Pathway
    'VG6PDH': {'name': 'Glucose-6-P Dehydrogenase', 'reaction': 'G6P + NADP ⇌ GL6P + NADPH', 'substrates': ['G6P', 'NADP'], 'products': ['GL6P', 'NADPH']},
    'VPGLS': {'name': 'Phosphogluconolactonase', 'reaction': 'GL6P → GO6P', 'substrates': ['GL6P'], 'products': ['GO6P']},
    'V6PGD': {'name': '6-Phosphogluconate Dehydrogenase', 'reaction': 'GO6P + NADP → RU5P + NADPH', 'substrates': ['GO6P', 'NADP'], 'products': ['RU5P', 'NADPH']},
    'VR5PI': {'name': 'Ribose-5-P Isomerase', 'reaction': 'RU5P ⇌ R5P', 'substrates': ['RU5P'], 'products': ['R5P']},
    'VR5PE': {'name': 'Ribulose-5-P 3-Epimerase', 'reaction': 'RU5P ⇌ X5P', 'substrates': ['RU5P'], 'products': ['X5P']},
    'VTKL1': {'name': 'Transketolase 1', 'reaction': 'X5P + R5P ⇌ GA3P + S7P', 'substrates': ['X5P', 'R5P'], 'products': ['GA3P', 'S7P']},
    'VTKL2': {'name': 'Transketolase 2', 'reaction': 'X5P + E4P ⇌ GA3P + F6P', 'substrates': ['X5P', 'E4P'], 'products': ['GA3P', 'F6P']},
    'VTAL': {'name': 'Transaldolase', 'reaction': 'S7P + GA3P ⇌ F6P + E4P', 'substrates': ['S7P', 'GA3P'], 'products': ['F6P', 'E4P']},
    
    # Transport reactions
    'VEGLC': {'name': 'Glucose Transport', 'reaction': 'GLC ⇌ EGLC', 'substrates': ['GLC'], 'products': ['EGLC']},
    'VELAC': {'name': 'Lactate Transport', 'reaction': 'LAC ⇌ ELAC', 'substrates': ['LAC'], 'products': ['ELAC']},
    'VEPYR': {'name': 'Pyruvate Transport', 'reaction': 'PYR ⇌ EPYR', 'substrates': ['PYR'], 'products': ['EPYR']},
    'VEADE': {'name': 'Adenine Transport', 'reaction': 'ADE ⇌ EADE', 'substrates': ['ADE'], 'products': ['EADE']},
    'VEINO': {'name': 'Inosine Transport', 'reaction': 'INO ⇌ EINO', 'substrates': ['INO'], 'products': ['EINO']},
    'VEADO': {'name': 'Adenosine Transport', 'reaction': 'ADO ⇌ EADO', 'substrates': ['ADO'], 'products': ['EADO']},
    'VEHYPX': {'name': 'Hypoxanthine Transport', 'reaction': 'HYPX ⇌ EHYPX', 'substrates': ['HYPX'], 'products': ['EHYPX']},
    'VEXAN': {'name': 'Xanthine Transport', 'reaction': 'XAN ⇌ EXAN', 'substrates': ['XAN'], 'products': ['EXAN']},
    'VEURT': {'name': 'Urate Transport', 'reaction': 'URT ⇌ EURT', 'substrates': ['URT'], 'products': ['EURT']},
    'VEGLN': {'name': 'Glutamine Transport', 'reaction': 'GLN ⇌ EGLN', 'substrates': ['GLN'], 'products': ['EGLN']},
    'VEGLU': {'name': 'Glutamate Transport', 'reaction': 'GLU ⇌ EGLU', 'substrates': ['GLU'], 'products': ['EGLU']},
    'VECYS': {'name': 'Cysteine Transport', 'reaction': 'CYS ⇌ ECYS', 'substrates': ['CYS'], 'products': ['ECYS']},
    'VEALA': {'name': 'Alanine Transport', 'reaction': 'ALA ⇌ EALA', 'substrates': ['ALA'], 'products': ['EALA']},
    'VEASP': {'name': 'Aspartate Transport', 'reaction': 'ASP ⇌ EASP', 'substrates': ['ASP'], 'products': ['EASP']},
    'VEMET': {'name': 'Methionine Transport', 'reaction': 'MET ⇌ EMET', 'substrates': ['MET'], 'products': ['EMET']},
    'VEMAL': {'name': 'Malate Transport', 'reaction': 'MAL ⇌ EMAL', 'substrates': ['MAL'], 'products': ['EMAL']},
    'VEFUM': {'name': 'Fumarate Transport', 'reaction': 'FUM ⇌ EFUM', 'substrates': ['FUM'], 'products': ['EFUM']},
    'VECIT': {'name': 'Citrate Transport', 'reaction': 'CIT ⇌ ECIT', 'substrates': ['CIT'], 'products': ['ECIT']},
    'VEUREA': {'name': 'Urea Transport', 'reaction': 'UREA ⇌ EUREA', 'substrates': ['UREA'], 'products': ['EUREA']},
    'VENH4': {'name': 'Ammonia Transport', 'reaction': 'NH4 ⇌ ENH4', 'substrates': ['NH4'], 'products': ['ENH4']},
    'VECYT': {'name': 'Cystine Transport', 'reaction': 'CYT ⇌ ECYT', 'substrates': ['CYT'], 'products': ['ECYT']},
    
    # Nucleotide Metabolism
    'VAK': {'name': 'Adenylate Kinase', 'reaction': '2 ADP ⇌ AMP + ATP', 'substrates': ['ADP'], 'products': ['AMP', 'ATP']},
    'VAK2': {'name': 'Adenosine Kinase', 'reaction': 'ADO + ATP → ADP + AMP', 'substrates': ['ADO', 'ATP'], 'products': ['ADP', 'AMP']},
    'VAPRT': {'name': 'Adenine Phosphoribosyltransferase', 'reaction': 'ADE + PRPP → AMP', 'substrates': ['ADE', 'PRPP'], 'products': ['AMP']},
    'VADA': {'name': 'Adenosine Deaminase', 'reaction': 'ADO → INO + NH4', 'substrates': ['ADO'], 'products': ['INO', 'NH4']},
    'VAMPD1': {'name': 'AMP Deaminase', 'reaction': 'AMP → IMP + NH4', 'substrates': ['AMP'], 'products': ['IMP', 'NH4']},
    'VHGPRT1': {'name': 'Hypoxanthine-Guanine Phosphoribosyltransferase 1', 'reaction': 'PRPP + HYPX → IMP', 'substrates': ['PRPP', 'HYPX'], 'products': ['IMP']},
    'VHGPRT2': {'name': 'Hypoxanthine-Guanine Phosphoribosyltransferase 2', 'reaction': 'GUA + AMP + PRPP → GMP', 'substrates': ['GUA', 'AMP', 'PRPP'], 'products': ['GMP']},
    'VGMPS': {'name': 'GMP Synthase', 'reaction': 'XMP + GLN + ATP → GMP + AMP', 'substrates': ['XMP', 'GLN', 'ATP'], 'products': ['GMP', 'AMP']},
    'VADSS': {'name': 'Adenylosuccinate Synthase', 'reaction': 'IMP + ASP + GTP → ADESUC + GDP', 'substrates': ['IMP', 'ASP', 'GTP'], 'products': ['ADESUC', 'GDP']},
    'VADSL': {'name': 'Adenylosuccinate Lyase', 'reaction': 'ADESUC ⇌ FUM + AMP', 'substrates': ['ADESUC'], 'products': ['FUM', 'AMP']},
    'VIMPH': {'name': 'IMP Dehydrogenase', 'reaction': 'IMP + NAD → XMP + NADH', 'substrates': ['IMP', 'NAD'], 'products': ['XMP', 'NADH']},
    'VPNPase1': {'name': 'Purine Nucleoside Phosphorylase', 'reaction': 'INO ⇌ HYPX + R1P', 'substrates': ['INO'], 'products': ['HYPX', 'R1P']},
    'VPRPPASE': {'name': 'PRPP Synthetase', 'reaction': 'R5P + ATP ⇌ PRPP + AMP', 'substrates': ['R5P', 'ATP'], 'products': ['PRPP', 'AMP']},
    'VRKa': {'name': 'Ribokinase', 'reaction': 'RIB + ATP ⇌ R5P + ADP', 'substrates': ['RIB', 'ATP'], 'products': ['R5P', 'ADP']},
    'VRKb': {'name': 'Ribose-1-P Isomerase', 'reaction': 'R1P ⇌ R5P', 'substrates': ['R1P'], 'products': ['R5P']},
    'VXAO': {'name': 'Xanthine Oxidase 1', 'reaction': 'HYPX → XAN + H2O2', 'substrates': ['HYPX'], 'products': ['XAN', 'H2O2']},
    'VXAO2': {'name': 'Xanthine Oxidase 2', 'reaction': 'XAN → URT', 'substrates': ['XAN'], 'products': ['URT']},
    'VOPRIBT': {'name': 'Orotidine Phosphoribosyltransferase', 'reaction': 'DEOXYINO ⇌ HYPX + D2RIBP', 'substrates': ['DEOXYINO'], 'products': ['HYPX', 'D2RIBP']},
    'Vnucleo2': {'name': 'IMP Nucleotidase', 'reaction': 'IMP → INO', 'substrates': ['IMP'], 'products': ['INO']},
    
    # Amino Acid Metabolism
    'VGLNS': {'name': 'Glutamine Synthetase', 'reaction': 'GLU + ATP + NH4 ⇌ GLN + ADP', 'substrates': ['GLU', 'ATP', 'NH4'], 'products': ['GLN', 'ADP']},
    'VGDH': {'name': 'Glutamate Dehydrogenase', 'reaction': 'AKG + NADPH + NH4 ⇌ GLU + NADP', 'substrates': ['AKG', 'NADPH', 'NH4'], 'products': ['GLU', 'NADP']},
    'VASPTA': {'name': 'Aspartate Aminotransferase', 'reaction': 'ASP + AKG ⇌ OAA + GLU', 'substrates': ['ASP', 'AKG'], 'products': ['OAA', 'GLU']},
    'VALATA': {'name': 'Alanine Aminotransferase', 'reaction': 'ALA + AKG ⇌ PYR + GLU', 'substrates': ['ALA', 'AKG'], 'products': ['PYR', 'GLU']},
    'VME': {'name': 'Malic Enzyme', 'reaction': 'MAL + NADP ⇌ PYR + NADPH', 'substrates': ['MAL', 'NADP'], 'products': ['PYR', 'NADPH']},
    'VPC': {'name': 'Pyruvate Carboxylase', 'reaction': 'PYR + ATP ⇌ OAA + ADP', 'substrates': ['PYR', 'ATP'], 'products': ['OAA', 'ADP']},
    'VACLY': {'name': 'ATP Citrate Lyase', 'reaction': 'OAA + ACCOA ⇌ CIT + COA + ATP', 'substrates': ['OAA', 'ACCOA'], 'products': ['CIT', 'COA', 'ATP']},
    'VASTA': {'name': 'Argininosuccinate Synthase', 'reaction': 'SUCCOA + ARG ⇌ COA + SUCARG', 'substrates': ['SUCCOA', 'ARG'], 'products': ['COA', 'SUCARG']},
    'VCYSGLY': {'name': 'Cysteinylglycine Dipeptidase', 'reaction': 'CYSGLY → CYS + GLY', 'substrates': ['CYSGLY'], 'products': ['CYS', 'GLY']},
    'VGGCT': {'name': 'Gamma-Glutamyl Cyclotransferase', 'reaction': 'GLUAA → OXOP + AA', 'substrates': ['GLUAA'], 'products': ['OXOP', 'AA']},
    'VMESE': {'name': 'Methionine Synthase', 'reaction': 'HCYS + METTHF ⇌ MET + THF', 'substrates': ['HCYS', 'METTHF'], 'products': ['MET', 'THF']},
    'VSAM': {'name': 'S-Adenosylmethionine Synthetase', 'reaction': 'MET + ATP → ADOMET', 'substrates': ['MET', 'ATP'], 'products': ['ADOMET']},
    'VSAH': {'name': 'S-Adenosylhomocysteine Hydrolase', 'reaction': 'ADOMET + CYT → SAH + METCYT', 'substrates': ['ADOMET', 'CYT'], 'products': ['SAH', 'METCYT']},
    'VAHCY': {'name': 'Adenosylhomocysteinase', 'reaction': 'SAH ⇌ HCYS + ADO', 'substrates': ['SAH'], 'products': ['HCYS', 'ADO']},
    'VCBS': {'name': 'Cystathionine Beta-Synthase', 'reaction': 'HCYS + SER ⇌ CYSTHIO', 'substrates': ['HCYS', 'SER'], 'products': ['CYSTHIO']},
    'VCSE': {'name': 'Cystathionine Gamma-Lyase', 'reaction': 'CYSTHIO ⇌ CYS + AKG + NH4', 'substrates': ['CYSTHIO'], 'products': ['CYS', 'AKG', 'NH4']},
    'VGENASP': {'name': 'PEP Carboxykinase', 'reaction': 'OAA + GTP → PEP + GDP', 'substrates': ['OAA', 'GTP'], 'products': ['PEP', 'GDP']},
    'VASL': {'name': 'Argininosuccinate Lyase', 'reaction': 'ARGSUC + ATP ⇌ ARG + ADP + FUM', 'substrates': ['ARGSUC', 'ATP'], 'products': ['ARG', 'ADP', 'FUM']},
    'VASS': {'name': 'Argininosuccinate Synthase', 'reaction': 'CITR + ASP + ATP ⇌ ARGSUC + AMP', 'substrates': ['CITR', 'ASP', 'ATP'], 'products': ['ARGSUC', 'AMP']},
    'Vpolyam': {'name': 'Arginase', 'reaction': 'ARG → ORN + UREA', 'substrates': ['ARG'], 'products': ['ORN', 'UREA']},
    
    # Redox Reactions
    'VGLUCYS': {'name': 'Gamma-Glutamylcysteine Synthetase', 'reaction': 'GLU + CYS + ATP → GLUCYS + ADP', 'substrates': ['GLU', 'CYS', 'ATP'], 'products': ['GLUCYS', 'ADP']},
    'VGSS': {'name': 'Glutathione Synthetase', 'reaction': 'GLUCYS + GLY + ATP → GSH + ADP', 'substrates': ['GLUCYS', 'GLY', 'ATP'], 'products': ['GSH', 'ADP']},
    'VGSR': {'name': 'Glutathione Reductase', 'reaction': 'GSSG + NADPH ⇌ 2 GSH + NADP', 'substrates': ['GSSG', 'NADPH'], 'products': ['GSH', 'NADP']},
    'VGPX': {'name': 'Glutathione Peroxidase', 'reaction': 'GSH + H2O2 → GSSG', 'substrates': ['GSH', 'H2O2'], 'products': ['GSSG']},
    'VGGT': {'name': 'Gamma-Glutamyltransferase', 'reaction': 'GSH + AA ⇌ GLUAA + CYSGLY', 'substrates': ['GSH', 'AA'], 'products': ['GLUAA', 'CYSGLY']},
    
    # 2,3-BPG Shunt
    'V23DPGP': {'name': '2,3-BPG Phosphatase', 'reaction': 'B23PG → P3G', 'substrates': ['B23PG'], 'products': ['P3G']},
    'VDPGM': {'name': '2,3-BPG Mutase', 'reaction': 'B13PG → B23PG', 'substrates': ['B13PG'], 'products': ['B23PG']},
    
    # Other
    'VFUM': {'name': 'Fumarase', 'reaction': 'FUM ⇌ MAL', 'substrates': ['FUM'], 'products': ['MAL']},
    'VMLD': {'name': 'Malate Dehydrogenase', 'reaction': 'MAL + NAD ⇌ OAA + NADH', 'substrates': ['MAL', 'NAD'], 'products': ['OAA', 'NADH']},
    'VH2O2': {'name': 'Catalase', 'reaction': 'H2O2 → O2', 'substrates': ['H2O2'], 'products': ['O2']},
}
