"""
Auto-Generated Curve Fitting Parameters for RBC Metabolites
======================================================================

Generated by: auto_fit_optimizer.py
Optimization method: Polynomial-logarithmic regression
Loss function: Least squares
Algorithm: Levenberg-Marquardt

Model: C(t) = a + b*t + c*t² + d*t³ + e*log(t+0.1)
"""

import numpy as np
from typing import Optional, Tuple


CURVE_FIT_PARAMS = {
    'ADE': {
        'coeffs': (0.62186722, -0.08418777, 0.00266498, -0.00002760, 0.07469652),
        'feedback': 2.00,
        'experimental_range': (0.005796, 0.589304),
        'r_squared': 0.9837,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted ADE'
    },
    'ADP': {
        'coeffs': (1.33199205, -0.20519571, 0.00687723, -0.00007863, 0.34563275),
        'feedback': 2.00,
        'experimental_range': (0.148953, 1.286340),
        'r_squared': 0.9800,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted ADP'
    },
    'ALA': {
        'coeffs': (0.62779744, 0.00000000, 0.00000000, 0.00000000, 0.00000000),
        'feedback': 1.00,
        'experimental_range': (0.456616, 0.778542),
        'r_squared': 1.0000,  # Goodness of fit
        'pattern': 'constant',  # Detected behavior pattern
        'description': 'Auto-fitted ALA'
    },
    'AMP': {
        'coeffs': (0.82616148, -0.09839931, 0.00417594, -0.00005205, 0.03686049),
        'feedback': 2.00,
        'experimental_range': (0.175863, 0.812804),
        'r_squared': 0.8997,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted AMP'
    },
    'ARG': {
        'coeffs': (0.02862988, -0.00193722, 0.00004426, -0.00000029, 0.00700028),
        'feedback': 4.00,
        'experimental_range': (0.020527, 0.043794),
        'r_squared': 0.1759,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted ARG'
    },
    'ASP': {
        'coeffs': (0.18515287, 0.00000000, 0.00000000, 0.00000000, 0.00000000),
        'feedback': 1.00,
        'experimental_range': (0.157767, 0.216223),
        'r_squared': 1.0000,  # Goodness of fit
        'pattern': 'constant',  # Detected behavior pattern
        'description': 'Auto-fitted ASP'
    },
    'ASN': {
        'coeffs': (0.45729116, -0.01494149, 0.00046046, -0.00000509, -0.00633135),
        'feedback': 1.00,
        'experimental_range': (0.198303, 0.485572),
        'r_squared': 0.9822,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted ASN'
    },
    'ATP': {
        'coeffs': (0.94469250, -0.07615367, 0.00079904, -0.00000138, 0.38914427),
        'feedback': 4.00,
        'experimental_range': (0.269483, 1.433145),
        'r_squared': 0.7576,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted ATP'
    },
    'B13PG': {
        'coeffs': (4.05263590, -0.51899069, 0.01551739, -0.00015340, 0.54430604),
        'feedback': 2.00,
        'experimental_range': (0.168417, 3.942450),
        'r_squared': 0.9959,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted B13PG'
    },
    'B23PG': {
        'coeffs': (4.05263590, -0.51899069, 0.01551739, -0.00015340, 0.54430604),
        'feedback': 2.00,
        'experimental_range': (0.168417, 3.942450),
        'r_squared': 0.9959,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted B23PG'
    },
    'CIT': {
        'coeffs': (0.10748989, -0.01755838, 0.00065924, -0.00000763, 0.02109342),
        'feedback': 2.00,
        'experimental_range': (0.018881, 0.102352),
        'r_squared': 0.9901,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted CIT'
    },
    'CITR': {
        'coeffs': (0.03545432, 0.00000000, 0.00000000, 0.00000000, 0.00000000),
        'feedback': 1.00,
        'experimental_range': (0.030213, 0.041884),
        'r_squared': 1.0000,  # Goodness of fit
        'pattern': 'constant',  # Detected behavior pattern
        'description': 'Auto-fitted CITR'
    },
    'EADE': {
        'coeffs': (0.49162780, -0.01295018, 0.00054698, -0.00000583, -0.12623736),
        'feedback': 2.00,
        'experimental_range': (0.004252, 0.514303),
        'r_squared': 0.9995,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted EADE'
    },
    'EASN': {
        'coeffs': (0.00906195, 0.00117808, -0.00004522, 0.00000050, 0.00645009),
        'feedback': 2.00,
        'experimental_range': (0.009905, 0.045362),
        'r_squared': 0.9803,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted EASN'
    },
    'ECIT': {
        'coeffs': (0.43956513, -0.00162231, -0.00002156, 0.00000031, -0.01778549),
        'feedback': 1.00,
        'experimental_range': (0.251889, 0.479084),
        'r_squared': 0.9904,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted ECIT'
    },
    'ECYS': {
        'coeffs': (-0.00133347, 0.00205283, -0.00002698, 0.00000009, -0.00525057),
        'feedback': 1.00,
        'experimental_range': (0.000000, 0.027490),
        'r_squared': 0.9963,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted ECYS'
    },
    'EFUM': {
        'coeffs': (0.01156300, 0.00003745, 0.00001349, -0.00000032, 0.00283316),
        'feedback': 1.00,
        'experimental_range': (0.010806, 0.030250),
        'r_squared': 0.9523,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted EFUM'
    },
    'EGLC': {
        'coeffs': (26.29138606, -1.07355948, 0.02668183, -0.00028383, 1.79861497),
        'feedback': 1.00,
        'experimental_range': (11.623500, 27.874000),
        'r_squared': 0.9948,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted EGLC'
    },
    'EGLN': {
        'coeffs': (0.04465635, -0.00898382, 0.00009842, -0.00000022, 0.06446850),
        'feedback': 2.00,
        'experimental_range': (0.039252, 0.134496),
        'r_squared': 0.9582,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted EGLN'
    },
    'EGLU': {
        'coeffs': (0.00362816, 0.00040396, -0.00000322, 0.00000001, 0.00429137),
        'feedback': 1.00,
        'experimental_range': (0.004195, 0.036547),
        'r_squared': 0.9790,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted EGLU'
    },
    'EGSSG': {
        'coeffs': (0.00730023, -0.00005487, 0.00000246, -0.00000002, -0.00213575),
        'feedback': 2.00,
        'experimental_range': (0.000014, 0.007752),
        'r_squared': 0.9987,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted EGSSG'
    },
    'EGSH': {
        'coeffs': (0.02007458, -0.00216034, 0.00005279, -0.00000043, 0.00256752),
        'feedback': 2.00,
        'experimental_range': (0.000000, 0.020144),
        'r_squared': 0.9873,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted EGSH'
    },
    'EHYPX': {
        'coeffs': (0.01411054, -0.01907590, 0.00092429, -0.00000901, 0.04300654),
        'feedback': 1.00,
        'experimental_range': (0.001502, 0.418029),
        'r_squared': 0.9987,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted EHYPX'
    },
    'EINO': {
        'coeffs': (0.00005434, -0.00009369, 0.00000359, -0.00000001, 0.00022316),
        'feedback': 2.00,
        'experimental_range': (0.000000, 0.003670),
        'r_squared': 0.9980,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted EINO'
    },
    'ELAC': {
        'coeffs': (2.47067220, 1.08102397, -0.01861540, 0.00014368, 0.44175984),
        'feedback': 1.00,
        'experimental_range': (3.252855, 31.200087),
        'r_squared': 0.9985,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted ELAC'
    },
    'EMAL': {
        'coeffs': (0.02879225, 0.00301011, -0.00001168, -0.00000010, 0.01253154),
        'feedback': 1.00,
        'experimental_range': (0.029619, 0.199151),
        'r_squared': 0.9951,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted EMAL'
    },
    'EARG': {
        'coeffs': (0.00165128, -0.00008957, 0.00000343, -0.00000004, -0.00012914),
        'feedback': 2.00,
        'experimental_range': (0.000451, 0.001698),
        'r_squared': 0.9828,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted EARG'
    },
    'PEP': {
        'coeffs': (0.23842089, -0.01603804, 0.00055949, -0.00000615, -0.02099754),
        'feedback': 2.00,
        'experimental_range': (0.009012, 0.241808),
        'r_squared': 0.9941,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted PEP'
    },
    'EURT': {
        'coeffs': (0.01474181, -0.00160550, 0.00001230, 0.00000009, 0.01058455),
        'feedback': 2.00,
        'experimental_range': (0.013196, 0.028339),
        'r_squared': 0.9205,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted EURT'
    },
    'EXAN': {
        'coeffs': (0.00038330, -0.00008740, 0.00000773, -0.00000008, 0.00024472),
        'feedback': 1.00,
        'experimental_range': (0.000312, 0.005885),
        'r_squared': 0.9963,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted EXAN'
    },
    'F16BP': {
        'coeffs': (0.09165938, -0.00530285, 0.00020061, -0.00000224, -0.01382986),
        'feedback': 2.00,
        'experimental_range': (0.002374, 0.093300),
        'r_squared': 0.9969,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted F16BP'
    },
    'F6P': {
        'coeffs': (0.05721413, 0.01162530, -0.00065380, 0.00000843, -0.00394452),
        'feedback': 2.00,
        'experimental_range': (0.006323, 0.142350),
        'r_squared': 0.9237,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted F6P'
    },
    'G6P': {
        'coeffs': (0.07266482, 0.00523757, -0.00041166, 0.00000576, 0.00687088),
        'feedback': 2.00,
        'experimental_range': (0.020010, 0.126614),
        'r_squared': 0.9623,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted G6P'
    },
    'GLC': {
        'coeffs': (1.16350212, -0.06701886, 0.00141389, -0.00001250, 0.25273436),
        'feedback': 1.00,
        'experimental_range': (0.743729, 1.403403),
        'r_squared': 0.9562,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted GLC'
    },
    'GLN': {
        'coeffs': (0.11421451, 0.00338586, -0.00020463, 0.00000245, -0.00878668),
        'feedback': 1.00,
        'experimental_range': (0.035938, 0.128333),
        'r_squared': 0.9906,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted GLN'
    },
    'GLU': {
        'coeffs': (0.50784469, -0.02660043, 0.00093845, -0.00001033, -0.03989611),
        'feedback': 2.00,
        'experimental_range': (0.100033, 0.521667),
        'r_squared': 0.9759,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted GLU'
    },
    'GMP': {
        'coeffs': (0.08377590, -0.00689230, 0.00028669, -0.00000352, -0.00592824),
        'feedback': 2.00,
        'experimental_range': (0.008214, 0.083648),
        'r_squared': 0.9812,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted GMP'
    },
    'GO6P': {
        'coeffs': (0.14266095, -0.01552570, 0.00053745, -0.00000595, 0.00546786),
        'feedback': 2.00,
        'experimental_range': (0.008039, 0.140998),
        'r_squared': 0.9984,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted GO6P'
    },
    'GSH': {
        'coeffs': (0.76327945, -0.09286265, 0.00253019, -0.00002480, 0.21730356),
        'feedback': 2.00,
        'experimental_range': (0.242751, 0.776019),
        'r_squared': 0.9287,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted GSH'
    },
    'GSSG': {
        'coeffs': (2.56005582, 0.07634097, -0.00683916, 0.00009268, 0.17317965),
        'feedback': 2.00,
        'experimental_range': (1.010370, 3.866821),
        'r_squared': 0.9290,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted GSSG'
    },
    'HYPX': {
        'coeffs': (0.07344540, -0.04350502, 0.00179011, -0.00001712, 0.10791496),
        'feedback': 2.00,
        'experimental_range': (0.040886, 0.683149),
        'r_squared': 0.9844,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted HYPX'
    },
    'IMP': {
        'coeffs': (0.09309813, 0.03213355, -0.00108025, 0.00001046, -0.05009267),
        'feedback': 4.00,
        'experimental_range': (0.084965, 0.320540),
        'r_squared': 0.6166,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted IMP'
    },
    'INO': {
        'coeffs': (0.00378468, -0.00127155, 0.00005562, -0.00000071, 0.00263179),
        'feedback': 4.00,
        'experimental_range': (0.001975, 0.008095),
        'r_squared': 0.7322,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted INO'
    },
    'LAC': {
        'coeffs': (0.66744145, 0.28093771, -0.00431503, 0.00002506, -0.04733965),
        'feedback': 1.00,
        'experimental_range': (0.858362, 7.537254),
        'r_squared': 0.9850,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted LAC'
    },
    'MAL': {
        'coeffs': (2.61253696, -0.23942999, 0.00713834, -0.00007705, 0.48677813),
        'feedback': 1.00,
        'experimental_range': (0.979217, 2.672501),
        'r_squared': 0.9864,  # Goodness of fit
        'pattern': 'decreasing',  # Detected behavior pattern
        'description': 'Auto-fitted MAL'
    },
    'OXOP': {
        'coeffs': (1.04675797, 0.03786994, 0.00275528, -0.00005116, 0.23257768),
        'feedback': 1.00,
        'experimental_range': (1.007464, 5.093251),
        'r_squared': 0.9937,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted OXOP'
    },
    'EOXOP': {
        'coeffs': (0.06154310, 0.05857352, -0.00128876, 0.00001196, 0.00186635),
        'feedback': 1.00,
        'experimental_range': (0.105842, 1.326105),
        'r_squared': 0.9987,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted EOXOP'
    },
    'P2G': {
        'coeffs': (0.34652969, -0.04574731, 0.00143753, -0.00001473, 0.03685070),
        'feedback': 2.00,
        'experimental_range': (0.000000, 0.332845),
        'r_squared': 0.9925,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted P2G'
    },
    'P3G': {
        'coeffs': (0.34652969, -0.04574731, 0.00143753, -0.00001473, 0.03685070),
        'feedback': 2.00,
        'experimental_range': (0.000000, 0.332845),
        'r_squared': 0.9925,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted P3G'
    },
    'PYR': {
        'coeffs': (0.96011274, 0.12118134, -0.00306964, 0.00002904, -0.32946177),
        'feedback': 1.00,
        'experimental_range': (0.903685, 1.787650),
        'r_squared': 0.9367,  # Goodness of fit
        'pattern': 'valley',  # Detected behavior pattern
        'description': 'Auto-fitted PYR'
    },
    'SAH': {
        'coeffs': (0.00252664, -0.00286563, 0.00007764, -0.00000076, 0.01198246),
        'feedback': 3.00,
        'experimental_range': (0.001074, 0.011087),
        'r_squared': 0.8220,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted SAH'
    },
    'ESER': {
        'coeffs': (0.07071246, 0.00324645, -0.00020663, 0.00000292, 0.01055756),
        'feedback': 2.00,
        'experimental_range': (0.070881, 0.143016),
        'r_squared': 0.5290,  # Goodness of fit
        'pattern': 'peak',  # Detected behavior pattern
        'description': 'Auto-fitted ESER'
    },
    'SER': {
        'coeffs': (0.02588110, 0.00000000, 0.00000000, 0.00000000, 0.00000000),
        'feedback': 1.00,
        'experimental_range': (0.020720, 0.033424),
        'r_squared': 1.0000,  # Goodness of fit
        'pattern': 'constant',  # Detected behavior pattern
        'description': 'Auto-fitted SER'
    },
    'URT': {
        'coeffs': (0.01547611, -0.00067781, 0.00003233, -0.00000042, -0.00276407),
        'feedback': 2.00,
        'experimental_range': (0.001497, 0.015991),
        'r_squared': 0.9889,  # Goodness of fit
        'pattern': 'complex',  # Detected behavior pattern
        'description': 'Auto-fitted URT'
    },
    'XAN': {
        'coeffs': (0.00012808, -0.00003179, 0.00000210, -0.00000002, 0.00010971),
        'feedback': 1.00,
        'experimental_range': (0.000102, 0.001886),
        'r_squared': 0.9960,  # Goodness of fit
        'pattern': 'increasing',  # Detected behavior pattern
        'description': 'Auto-fitted XAN'
    },
    
    # ==== METABOLITES FORCED TO CONSTANT VALUES (No experimental data) ====
    # These metabolites go negative without constraints, so we force them constant
    
    'ADO': {  # Adenosine (intracellular, x[26])
        'coeffs': (0.0012, 0.0, 0.0, 0.0, 0.0),  # Constant at initial value
        'feedback': 50.0,  # Very strong forcing
        'experimental_range': (0.0005, 0.0020),
        'r_squared': 1.0000,  # Perfect by definition (constant)
        'pattern': 'constant',
        'description': 'Forced constant to prevent negative values'
    },
    
    'E4P': {  # Erythrose 4-phosphate (x[8])
        'coeffs': (1.77, 0.0, 0.0, 0.0, 0.0),  # Constant at initial value
        'feedback': 50.0,  # Very strong forcing
        'experimental_range': (1.5, 2.0),
        'r_squared': 1.0000,
        'pattern': 'constant',
        'description': 'Forced constant to prevent negative values'
    },
    
    'EUREA': {  # Extracellular urea (x[96])
        'coeffs': (6.0746, 0.0, 0.0, 0.0, 0.0),  # Constant at initial value
        'feedback': 50.0,  # Very strong forcing
        'experimental_range': (5.5, 6.5),
        'r_squared': 1.0000,
        'pattern': 'constant',
        'description': 'Forced constant to prevent negative values'
    },
    
    'NADH': {  # NADH (x[76])
        'coeffs': (0.002738, 0.0, 0.0, 0.0, 0.0),  # Constant at initial value
        'feedback': 50.0,  # Very strong forcing
        'experimental_range': (0.001, 0.005),
        'r_squared': 1.0000,
        'pattern': 'constant',
        'description': 'Forced constant to prevent negative values'
    },
    
    'NADPH': {  # NADPH (x[78])
        'coeffs': (0.001552, 0.0, 0.0, 0.0, 0.0),  # Constant at initial value
        'feedback': 50.0,  # Very strong forcing
        'experimental_range': (0.0005, 0.003),
        'r_squared': 1.0000,
        'pattern': 'constant',
        'description': 'Forced constant to prevent negative values'
    },
    
    'ENH4': {  # Extracellular ammonia (x[86]) - OVERRIDE auto-generated
        'coeffs': (0.0, 0.0, 0.0, 0.0, 0.0),  # Force to zero
        'feedback': 100.0,  # EXTREME forcing (was 50.0, increased)
        'experimental_range': (0.0, 0.0001),
        'r_squared': 1.0000,
        'pattern': 'zero',
        'description': 'Forced to zero - no ammonia production'
    },
    
    'EALA': {  # Extracellular alanine (x[104]) - OVERRIDE auto-generated
        'coeffs': (0.0, 0.0, 0.0, 0.0, 0.0),  # Force to zero
        'feedback': 100.0,  # EXTREME forcing (was 30.0, increased)
        'experimental_range': (0.0, 0.0001),
        'r_squared': 1.0000,
        'pattern': 'zero',
        'description': 'Forced to zero - no alanine efflux'
    },
}


def compute_target_concentration(metabolite: str, t: float) -> Optional[float]:
    """
    Compute target concentration for a metabolite at time t using polynomial-log model.
    
    Args:
        metabolite: Name of the metabolite
        t: Time in hours
    
    Returns:
        Target concentration in mM, or None if metabolite not found
    """
    if metabolite not in CURVE_FIT_PARAMS:
        return None
    
    params = CURVE_FIT_PARAMS[metabolite]
    a, b, c, d, e = params["coeffs"]
    
    # C(t) = a + b*t + c*t² + d*t³ + e*log(t+0.1)
    target = a + b * t + c * t**2 + d * t**3 + e * np.log(t + 0.1)
    
    # Clamp to experimental range
    min_val, max_val = params["experimental_range"]
    target = np.clip(target, min_val, max_val)
    
    return float(target)


def get_curve_fit_correction(metabolite: str, t: float, current_conc: float,
                            curve_fit_strength: float = 1.0) -> float:
    """
    Calculate the correction term for curve fitting.
    
    Args:
        metabolite: Name of the metabolite
        t: Current time in hours
        current_conc: Current concentration in mM
        curve_fit_strength: Blending parameter (0=pure MM, 1=pure fitting)
    
    Returns:
        Correction term to add to dC/dt
    """
    target_conc = compute_target_concentration(metabolite, t)
    if target_conc is None:
        return 0.0
    
    params = CURVE_FIT_PARAMS[metabolite]
    feedback = params["feedback"]
    
    # Proportional feedback control
    error = target_conc - current_conc
    correction = curve_fit_strength * feedback * error
    
    return correction
